server:
  port: 8030

spring:
  application:
    name: spring-cloud-euraka-client
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/